allure

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -16,73 +16,73 @@ on:
         required: true
         type: boolean
 jobs:
-  run_containers_on_VM:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: shimataro/ssh-key-action@v2
-        with:
-          key: ${{ secrets.PRIVATE_KEY }}
-          known_hosts: ${{ secrets.SSH_HOST }}
-      - name: ssh connection and start docker containers
-        run: ssh valera@${{ secrets.HOST_IP }}
-          "./cm selenoid start &
-          docker start pdp-postgres &
-          exit"
-  tests:
-    #    strategy:
-    #      matrix:
-    #        browser: [ chrome, firefox ]
-    runs-on: ubuntu-latest
-    needs: run_containers_on_VM
-    steps:
-      - name: Setup java
-        uses: actions/setup-java@v3
-        with:
-          distribution: 'adopt'
-          java-version: 11
-      - name: Checkout project sources
-        uses: actions/checkout@v3
-      - name: Gradle
-        uses: gradle/gradle-build-action@v2
-      - name: Execute ${{ github.event.inputs.test_job }} task
-        run: ./gradlew clean ${{ github.event.inputs.test_job }} -Dbrowser=chrome
-      - name: Generate allure report
-        if: ${{ (success() || failure()) && (github.event.inputs.allure == 'true') }}
-        run: echo "WTF"
-      - name: Upload artifacts
-        if: always()
-        uses: actions/upload-artifact@v3
-        with:
-          name: allure-results
-          path: build/allure-results
-
-  artifact:
-    needs: tests
-    runs-on: ubuntu-latest
-    if: always()
-    steps:
-      - name: Get allure results artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: allure-results
-
-  stop_containers_on_VM:
-    runs-on: ubuntu-latest
-    needs: tests
-    if: always()
-    steps:
-      - uses: shimataro/ssh-key-action@v2
-        with:
-          key: ${{ secrets.PRIVATE_KEY }}
-          known_hosts: ${{ secrets.SSH_HOST }}
-      - name: ssh connection and stop docker containers
-        run: ssh valera@${{ secrets.HOST_IP }} "./cm selenoid stop &
-          docker stop pdp-postgres &
-          exit"
+#  run_containers_on_VM:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: shimataro/ssh-key-action@v2
+#        with:
+#          key: ${{ secrets.PRIVATE_KEY }}
+#          known_hosts: ${{ secrets.SSH_HOST }}
+#      - name: ssh connection and start docker containers
+#        run: ssh valera@${{ secrets.HOST_IP }}
+#          "./cm selenoid start &
+#          docker start pdp-postgres &
+#          exit"
+#  tests:
+#    #    strategy:
+#    #      matrix:
+#    #        browser: [ chrome, firefox ]
+#    runs-on: ubuntu-latest
+#    needs: run_containers_on_VM
+#    steps:
+#      - name: Setup java
+#        uses: actions/setup-java@v3
+#        with:
+#          distribution: 'adopt'
+#          java-version: 11
+#      - name: Checkout project sources
+#        uses: actions/checkout@v3
+#      - name: Gradle
+#        uses: gradle/gradle-build-action@v2
+#      - name: Execute ${{ github.event.inputs.test_job }} task
+#        run: ./gradlew clean ${{ github.event.inputs.test_job }} -Dbrowser=chrome
+#      - name: Generate allure report
+#        if: ${{ (success() || failure()) && (github.event.inputs.allure == 'true') }}
+#        run: echo "WTF"
+#      - name: Upload artifacts
+#        if: always()
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: allure-results
+#          path: build/allure-results
+#
+#  artifact:
+#    needs: tests
+#    runs-on: ubuntu-latest
+#    if: always()
+#    steps:
+#      - name: Get allure results artifacts
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: allure-results
+#
+#  stop_containers_on_VM:
+#    runs-on: ubuntu-latest
+#    needs: tests
+#    if: always()
+#    steps:
+#      - uses: shimataro/ssh-key-action@v2
+#        with:
+#          key: ${{ secrets.PRIVATE_KEY }}
+#          known_hosts: ${{ secrets.SSH_HOST }}
+#      - name: ssh connection and stop docker containers
+#        run: ssh valera@${{ secrets.HOST_IP }} "./cm selenoid stop &
+#          docker stop pdp-postgres &
+#          exit"
 
   generate_allure_results:
     runs-on: ubuntu-latest
-    needs: artifact
+#    needs: artifact
     if: ${{ always() && (github.event.inputs.allure == 'true') }}
     steps:
       - uses: shimataro/ssh-key-action@v2
